spring:
  security:
    user:
      name: qa
      password: qa
      roles: "USER"
  docker:
    compose:
      enabled: false



logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"

  level:
    org:
      springframework:
        cloud:
          openfeign: debug
        web: debug
    br:
      fiap:
        pos:
          qualidade:
            qa: debug
    root: info